### ISSUE TITLE
🔃 Jokes not refreshing quickly

### ISSUE THREAD

**Issue by ABSphreak** [ABSphreak/readme-jokes#2]
Refreshing the jokes takes about an hour due to image caching.

Can be solved by solving #4

**Comment by ABSphreak** [comment]
@karmanya007 this was the issue that you worked on, lol.

**Comment by ABSphreak** [comment]
fixed in #18 by @karmanya007

**Comment by karmanya007** [comment]
😁

**Comment by anuraghazra** [comment]
I'm pretty sure you don't need 1 hour of cache since you are not hitting any APIs you are just getting the jokes from the local file system.

**Comment by ABSphreak** [comment]
@anuraghazra should I remove it? would it mess up the randomization time?

**Comment by anuraghazra** [comment]
I think you can remove the caching safely and if you got lot more serverless execution in future you can make it 30min cache..

**Comment by ABSphreak** [comment]
@anuraghazra thanks for the friendly tip! I would remove it.
Previously when I did that, on Vercel deployment it was working fine,
but on Github READMEs it was not working.
Would have to do some testing.
