### ISSUE TITLE
📱 Not Mobile responsive.

### ISSUE THREAD

**Issue by ABSphreak** [ABSphreak/readme-jokes#3]
Jokes' card is not mobile responsive.

![image](https://user-images.githubusercontent.com/9509127/95679122-57e9e380-0bee-11eb-8da8-f919aa7fc05a.png)

**Comment by NOPROD** [comment]
Hi, does you have access to css media queries ? Or we need to make responsive without ? (pure js)

**Comment by NOPROD** [comment]
Desktop:
![desktop](https://user-images.githubusercontent.com/38657472/96528578-68036200-1283-11eb-9639-7f65e0e500ae.PNG)

Mobile
![mobile](https://user-images.githubusercontent.com/38657472/96528580-689bf880-1283-11eb-8844-8510f1319abd.png)

And we keep 50% of size on desktop, 100% only on mobile?

Wanna make the fonts bigger on mobile?

**Comment by NOPROD** [comment]
Impossible, i try and i realise it's impossible haha. (with git)

We can't get any information from user device, so we can't make and api call with generated variables like `window.innerHeight`.

You can only render your jokes as an jpg image with markdown cause is parsed (cause you download it with <img src="http..."/> and something like <div :html=""> don't existe)

So, if you wan't help we can make a render who like great on mobile and desktop.

**Comment by ABSphreak** [comment]
@NOPROD you have github-readme-stats on your profile, check those on mobile, working fine. I wanted something similar, but it should also adjust to the text that is given in the card.

**Comment by anuraghazra** [comment]
try setting proper viewbox on the SVG and don't use any units on the width, height. just give them `width="100"`, `height="100"` 

And yes you cannot make use of responsive text sizes, just make your card maintain it's aspect ratio.. thats best you can do i think.

**Comment by ABSphreak** [comment]
@anuraghazra I tried doing that, but text was clipping if it was more than 50 characters in one line, so I made it choose the viewbox itself. Do I make a text-breaking mechanism, if it exceeds a certain word per line limit?

**Comment by anuraghazra** [comment]
Yeah you can do that we also have that in github-readme-stats

https://github.com/anuraghazra/github-readme-stats/blob/master/src/common/utils.js#L145-L160

**Comment by ABSphreak** [comment]
Great! I will fix it soon.
Thanks for the tips @anuraghazra, really appreciate it.
I will connect on Discord if I'm stuck somewhere.
