### ISSUE TITLE
How to use the parameters?

### ISSUE THREAD

**Issue by mirzafahad** [ABSphreak/readme-jokes#35]
Couldn't figure out how to use the parameters. Like, how to change the bgcolor. Can you provide an example?

**Comment by ABSphreak** [comment]
Hey @mirzafahad,
Thanks for reaching out.

You can change the colors on the card using following URL parameters:
- `bgColor` → **Background Color**
- `borderColor` → **Border Color**
- `qColor` → **Question Color**
- `aColor` → **Answer Color**
- `textColor` → **Normal text Color**
- `codeColor` → **Code Color**
- `theme` → **Theme (Must be one of the following)**

**Example** → If you want to change the `bgColor` to **#1b4332**, you would change the `#` symbol with `%23` in URL and keep the color code same like this:

```sh
https://readme-jokes.vercel.app/api?bgColor=%231b4332
```

Hope it answers your query.
Reopen this issue or just comment on the thread if you have any further doubts/suggestions.

**Comment by mirzafahad** [comment]
Thank you very much!
