### ISSUE TITLE
Readme-jokes is not working!

### ISSUE THREAD

**Issue by Ankit-jailwal** [ABSphreak/readme-jokes#42]
![joke](https://user-images.githubusercontent.com/55527244/121772893-fc656080-cb95-11eb-9d73-99201258f954.PNG)

**Comment by Adatta1276** [comment]
Yes, it's true, please do fix this, as a LOT of us have these jokes on our READMEs.

**Comment by ABSphreak** [comment]
Thanks, @Adatta1276 and @Ankit-jailwal for pointing out. It has been fixed now.
