### ISSUE TITLE
Issue with color theme

### ISSUE THREAD

**Issue by SrNightmare09** [ABSphreak/readme-jokes#43]
So I'm actually making my README, but i copy pasted this:
```bash
<img src="https://readme-jokes.vercel.app/api?theme=solidBlue" alt="Jokes Card" />
```

However, the theme of the card does not seem to cahnge and remains as the original color.

I think i have added the params properly after seeing your examples.

**Comment by ABSphreak** [comment]
As of right now `solidBlue`, `gradientBlue`, `daySky` are not working properly, I will solve this issue as soon as possible.
For now you can use customization parameters to customize the look of the card on your profile.
Thanks for pointing out.

**Comment by SrNightmare09** [comment]
> As of right now `solidBlue`, `gradientBlue`, `daySky` are not working properly, I will solve this issue as soon as possible.
> For now you can use customization parameters to customize the look of the card on your profile.
> Thanks for pointing out.

Thanks for consulting the problem to me!

**Comment by ABSphreak** [comment]
Update: `solidBlue`, `gradientBlue`, `daySky` are fixed now. There is a slight issue with `daySky`'s color contrast, but everything else is fine.
