### ISSUE TITLE
Add Customization Parameter for Hiding Border

### ISSUE THREAD

**Issue by jash-desai** [ABSphreak/readme-jokes#48]
Make a bool parameter for hiding the borders of the box
like the one in 
https://github-readme-stats.vercel.app/api/top-langs?

this has a bool parameter hide_border which can true/false.
It would be really helpful!

**Comment by ABSphreak** [comment]
Thanks for the suggestion @jash-desai.
Added in [this commit](https://github.com/ABSphreak/readme-jokes/commit/d703554a3d073802defc03f088a778f315c96790).
