### ISSUE TITLE
⚡ Improve the look for the Jokes Card

### ISSUE THREAD

**Issue by ABSphreak** [ABSphreak/readme-jokes#6]
Improve the look of the Jokes card.

check → [`index.js`](https://github.com/ABSphreak/readme-jokes/blob/master/api/index.js)

**Comment by MansiAyer** [comment]
hi, I'm interested in contributing. Can I take on this issue?

**Comment by ABSphreak** [comment]
@MansiAyer yeah sure, develop on it.

**Comment by MansiAyer** [comment]
👍

**Comment by sameer882000** [comment]
How about adding different themes?

**Comment by MansiAyer** [comment]
@sameer882000 yep, that's exactly what I'm trying to do. I've already started making different themes, but tbh I'm not too familiar with vercel so I'm not sure how the functionality of switching between such themes can be added. If you know how theme switching can be done please do explain it to me🙌

**Comment by ABSphreak** [comment]
@MansiAyer Vercel is a serverless deployment platform, so this whole deployment actually works from [`api/index.js`](https://github.com/ABSphreak/readme-jokes/blob/master/api/index.js), you can refer [anuraghazra/github-readme-stats](https://github.com/anuraghazra/github-readme-stats) as that has been the inspiration for this project too.
