### ISSUE TITLE
Image is shrinked on Github

### ISSUE THREAD

**Issue by poblouin** [ABSphreak/readme-jokes#66]
# Summary

The image height is shrinked on Github (markdown) for some reason. I noticed it few days ago, not sure how long it's been like that.

System:
Macbook Air M1 2020
Monterey 12.0.1
Firefox 94.0.2

# How To Reproduce

Just look at the README of the repo, you can see the issue there. It's the same in my own README. I haven't try the HTML version, only the markdown.

<img width="522" alt="Screen Shot 2021-12-04 at 8 41 24 AM" src="https://user-images.githubusercontent.com/7467410/144711719-b2e7b2f2-2a0b-465d-9402-b7b351249e24.png">

Do someone have an idea of what is going on or noticed the same issue as I do? I never worked on this project, but I'll try to take some time to investigate and find a fix.

**Comment by ABSphreak** [comment]
Happens on Firefox and Mobile.
#3 & #46.

**Comment by poblouin** [comment]
Ah thanks, I wasn't sure that #46 was related.

**Comment by poblouin** [comment]
@ABSphreak Forcing the width and height seems to fix the issue: https://github.com/poblouin/readme-jokes/pull/1. You can test using the Vercel URL from the build.

That's not enough though, we would need to dynamically adapt those values based on the content of the card. That's a start, but I don't think I am good enough at CSS + SVG to properly solve it 😅

**Comment by ABSphreak** [comment]
Closed in #68, I think.

**Comment by poblouin** [comment]
@ABSphreak The issue is still present, I still see it on Firefox when I look at the README of the repo.
<img width="596" alt="Screen Shot 2022-04-21 at 7 07 13 PM" src="https://user-images.githubusercontent.com/7467410/164565503-0b9cfe96-bc2b-412f-8279-26f0b6d4b80b.png">

**Comment by ABSphreak** [comment]
@poblouin would look into it
